//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salem.Utils.Image_Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CountryFlags_Square64 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CountryFlags_Square64() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Salem.Utils.Image_Resources.CountryFlags_Square64", typeof(CountryFlags_Square64).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Afghanistan_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Afghanistan_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Albania_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Albania_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Algeria_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Algeria_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Andorra_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Andorra_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Angola_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Angola_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Antarctica_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Antarctica_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Antigua_and_Barbuda_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Antigua_and_Barbuda_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Argentina_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Argentina_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Armenia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Armenia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Artsakh_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Artsakh_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Australia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Australia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Austria_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Austria_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Azerbaijan_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Azerbaijan_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Bahamas_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Bahamas_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Bahrain_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Bahrain_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Bangladesh_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Bangladesh_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Barbados_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Barbados_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Belarus_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Belarus_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Belgium_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Belgium_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Belize_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Belize_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Benin_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Benin_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Bhutan_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Bhutan_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Bolivia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Bolivia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Bosnia_and_Herzegovina_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Bosnia_and_Herzegovina_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Botswana_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Botswana_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Brazil_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Brazil_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Brunei_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Brunei_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Bulgaria_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Bulgaria_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Burkina_Faso_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Burkina_Faso_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Burundi_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Burundi_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Cambodia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Cambodia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Cameroon_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Cameroon_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Canada_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Canada_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Cape_Verde_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Cape_Verde_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Central_African_Republic_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Central_African_Republic_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Chad_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Chad_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Chile_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Chile_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Colombia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Colombia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Comoros_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Comoros_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Cook_Islands_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Cook_Islands_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Costa_Rica_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Costa_Rica_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Côte_dIvoire_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Côte_dIvoire_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Croatia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Croatia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Cuba_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Cuba_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Cyprus_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Cyprus_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Czech_Republic_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Czech_Republic_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Democratic_Republic_of_Congo_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Democratic_Republic_of_Congo_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Denmark_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Denmark_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Djibouti_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Djibouti_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Dominica_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Dominica_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Dominican_Republic_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Dominican_Republic_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_East_Timor_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_East_Timor_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Ecuador_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Ecuador_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Egypt_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Egypt_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_El_Salvador_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_El_Salvador_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_England_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_England_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Equatorial_Guinea_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Equatorial_Guinea_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Eritrea_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Eritrea_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Estonia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Estonia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Eswatini_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Eswatini_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Ethiopia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Ethiopia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Faroe_Islands_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Faroe_Islands_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Federated_States_of_Micronesia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Federated_States_of_Micronesia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Fiji_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Fiji_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Finland_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Finland_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_France_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_France_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_French_Guiana_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_French_Guiana_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Gabon_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Gabon_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Gambia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Gambia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Georgia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Georgia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Germany_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Germany_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Ghana_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Ghana_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Gibraltar_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Gibraltar_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Greece_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Greece_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Grenada_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Grenada_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Guatemala_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Guatemala_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Guinea_Bissau_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Guinea-Bissau_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Guinea_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Guinea_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Guyana_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Guyana_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Haiti_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Haiti_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Honduras_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Honduras_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Hong_Kong_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Hong_Kong_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Hungary_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Hungary_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Iceland_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Iceland_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_India_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_India_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Indonesia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Indonesia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Iran_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Iran_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Iraq_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Iraq_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Ireland_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Ireland_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Isle_of_Mann_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Isle_of_Mann_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Israel_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Israel_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Italy_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Italy_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Jamaica_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Jamaica_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Japan_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Japan_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Jordan_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Jordan_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Kazakhstan_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Kazakhstan_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Kenya_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Kenya_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Kiribati_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Kiribati_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Kosovo_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Kosovo_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Kuwait_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Kuwait_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Kyrgyzstan_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Kyrgyzstan_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Laos_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Laos_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Latvia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Latvia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Lebanon_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Lebanon_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Lesotho_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Lesotho_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Liberia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Liberia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Libya_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Libya_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Liechtenstein_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Liechtenstein_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Lithuania_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Lithuania_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Luxembourg_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Luxembourg_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Macau_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Macau_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Madagascar_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Madagascar_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Malawi_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Malawi_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Malaysia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Malaysia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Maldives_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Maldives_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Mali_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Mali_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Malta_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Malta_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Marshall_Islands_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Marshall_Islands_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Mauritania_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Mauritania_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Mauritius_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Mauritius_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Mayotte_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Mayotte_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Mexico_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Mexico_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Moldova_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Moldova_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Monaco_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Monaco_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Mongolia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Mongolia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Montenegro_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Montenegro_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Morocco_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Morocco_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Mozambique_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Mozambique_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Myanmar_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Myanmar_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Namibia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Namibia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Nauru_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Nauru_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Nepal_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Nepal_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Netherlands_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Netherlands_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_New_Zealand_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_New_Zealand_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Nicaragua_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Nicaragua_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Niger_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Niger_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Nigeria_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Nigeria_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Niue_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Niue_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_North_Korea_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_North_Korea_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_North_Macedonia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_North_Macedonia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Norway_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Norway_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Oman_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Oman_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Pakistan_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Pakistan_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Palau_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Palau_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Palestine_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Palestine_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Panama_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Panama_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Papua_New_Guinea_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Papua_New_Guinea_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Paraguay_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Paraguay_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Peoples_Republic_of_China_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Peoples_Republic_of_China_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Peru_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Peru_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Philippines_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Philippines_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Poland_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Poland_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Portugal_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Portugal_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Qatar_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Qatar_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Republic_of_Abkhazia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Republic_of_Abkhazia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Republic_of_Congo_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Republic_of_Congo_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Reunion_Radiant_Volcano_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Reunion_Radiant_Volcano_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Romania_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Romania_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Russia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Russia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Rwanda_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Rwanda_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Sahrawi_Arab_Democratic_Republic_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Sahrawi_Arab_Democratic_Republic_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Saint_Helena_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Saint_Helena_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Saint_Kitts_and_Nevis_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Saint_Kitts_and_Nevis_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Saint_Lucia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Saint_Lucia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Saint_Vincent_and_the_Grenadines_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Saint_Vincent_and_the_Grenadines_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Samoa_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Samoa_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_San_Marino_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_San_Marino_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Sao_Tome_and_Principe_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Sao_Tome_and_Principe_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Saudi_Arabia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Saudi_Arabia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Scotland_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Scotland_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Senegal_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Senegal_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Serbia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Serbia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Seychelles_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Seychelles_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Sierra_Leone_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Sierra_Leone_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Singapore_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Singapore_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Slovakia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Slovakia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Slovenia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Slovenia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Solomon_Islands_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Solomon_Islands_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Somalia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Somalia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Somaliland_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Somaliland_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_South_Africa_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_South_Africa_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_South_Korea_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_South_Korea_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_South_Ossetia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_South_Ossetia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_South_Sudan_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_South_Sudan_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Spain_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Spain_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Sri_Lanka_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Sri_Lanka_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Sudan_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Sudan_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Suriname_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Suriname_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Sweden_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Sweden_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Switzerland_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Switzerland_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Syria_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Syria_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Taiwan_Republic_of_China_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Taiwan_Republic_of_China_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Tajikistan_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Tajikistan_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Tanzania_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Tanzania_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Thailand_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Thailand_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Togo_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Togo_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Tonga_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Tonga_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Transnistria_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Transnistria_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Trinidad_and_Tobago_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Trinidad_and_Tobago_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Tunisia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Tunisia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Turkey_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Turkey_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Turkish_Republic_of_Northern_Cyprus_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Turkish_Republic_of_Northern_Cyprus_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Turkmenistan_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Turkmenistan_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Tuvalu_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Tuvalu_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Uganda_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Uganda_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Ukraine_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Ukraine_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_United_Arab_Emirates_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_United_Arab_Emirates_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_United_Kingdom_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_United_Kingdom_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_United_States_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_United_States_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Uruguay_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Uruguay_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Uzbekistan_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Uzbekistan_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Vanuatu_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Vanuatu_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Vatican_City_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Vatican_City_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Venezuela_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Venezuela_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Vietnam_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Vietnam_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Wales_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Wales_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Yemen_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Yemen_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Zambia_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Zambia_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Flag_of_Zimbabwe_Flat_Square_64x64 {
            get {
                object obj = ResourceManager.GetObject("Flag_of_Zimbabwe_Flat_Square-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap No_Image_64x64 {
            get {
                object obj = ResourceManager.GetObject("No_Image-64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
