using Salem.Utils.Image_Resources;
using Salem.Utils.String_Resources;

namespace Salem.Utils {
    public static class LocalizedRetriever {
        public static string[] GetCountryNames() => new string[] {
            CountryNames.Afghanistan, CountryNames.Albania, CountryNames.Algeria,
            CountryNames.Andorra, CountryNames.Angola, CountryNames.AntiguaAndBarbuda,
            CountryNames.Argentina, CountryNames.Armenia, CountryNames.Austria,
            CountryNames.Azerbaijan, CountryNames.Bahrain, CountryNames.Bangladesh,
            CountryNames.Barbados, CountryNames.Belarus, CountryNames.Belgium,
            CountryNames.Belize, CountryNames.Benin, CountryNames.Bhutan,
            CountryNames.Bolivia, CountryNames.BosniaAndHerzegovina, CountryNames.Botswana,
            CountryNames.Brazil, CountryNames.Brunei, CountryNames.Bulgaria,
            CountryNames.BurkinaFaso, CountryNames.Burundi, CountryNames.CaboVerde,
            CountryNames.Cambodia, CountryNames.Cameroon, CountryNames.Canada,
            CountryNames.CentralAfricanRepublic, CountryNames.Chad, CountryNames.ChannelIslands,
            CountryNames.Chile, CountryNames.China, CountryNames.Colombia,
            CountryNames.Comoros, CountryNames.Congo, CountryNames.CostaRica,
            CountryNames.CôtedIvoire, CountryNames.Croatia, CountryNames.Cuba,
            CountryNames.Cyprus, CountryNames.CzechRepublic, CountryNames.Denmark,
            CountryNames.Djibouti, CountryNames.Dominica, CountryNames.DominicanRepublic,
            CountryNames.DRCongo, CountryNames.Ecuador, CountryNames.Egypt,
            CountryNames.ElSalvador, CountryNames.EquatorialGuinea, CountryNames.Eritrea,
            CountryNames.Estonia, CountryNames.Eswatini, CountryNames.Ethiopia,
            CountryNames.FaeroeIslands, CountryNames.Finland, CountryNames.France,
            CountryNames.FrenchGuiana, CountryNames.Gabon, CountryNames.Gambia,
            CountryNames.Georgia, CountryNames.Germany, CountryNames.Ghana,
            CountryNames.Gibraltar, CountryNames.Greece, CountryNames.Grenada,
            CountryNames.Guatemala, CountryNames.Guinea, CountryNames.GuineaBissau,
            CountryNames.Guyana, CountryNames.Haiti, CountryNames.HolySee,
            CountryNames.Honduras, CountryNames.HongKong, CountryNames.Hungary,
            CountryNames.Iceland, CountryNames.India, CountryNames.Indonesia,
            CountryNames.Iran, CountryNames.Iraq, CountryNames.Ireland,
            CountryNames.IsleofMan, CountryNames.Israel, CountryNames.Italy,
            CountryNames.Jamaica, CountryNames.Japan, CountryNames.Jordan,
            CountryNames.Kazakhstan, CountryNames.Kenya, CountryNames.Kuwait,
            CountryNames.Kyrgyzstan, CountryNames.Laos, CountryNames.Latvia,
            CountryNames.Lebanon, CountryNames.Lesotho, CountryNames.Liberia,
            CountryNames.Libya, CountryNames.Liechtenstein, CountryNames.Lithuania,
            CountryNames.Luxembourg, CountryNames.Macao, CountryNames.Madagascar,
            CountryNames.Malawi, CountryNames.Malaysia, CountryNames.Maldives,
            CountryNames.Mali, CountryNames.Malta, CountryNames.Mauritania,
            CountryNames.Mauritius, CountryNames.Mayotte, CountryNames.Mexico,
            CountryNames.Moldova, CountryNames.Monaco, CountryNames.Mongolia,
            CountryNames.Montenegro, CountryNames.Morocco, CountryNames.Mozambique,
            CountryNames.Myanmar, CountryNames.Namibia, CountryNames.Nepal,
            CountryNames.Netherlands, CountryNames.Nicaragua, CountryNames.Niger,
            CountryNames.Nigeria, CountryNames.NorthKorea, CountryNames.NorthMacedonia,
            CountryNames.Norway, CountryNames.Oman, CountryNames.Pakistan, 
            CountryNames.Palestine, CountryNames.Panama, CountryNames.Paraguay,
            CountryNames.Peru, CountryNames.Philippines, CountryNames.Poland, 
            CountryNames.Portugal, CountryNames.Qatar, CountryNames.Réunion, 
            CountryNames.Romania, CountryNames.Russia, CountryNames.Rwanda,
            CountryNames.SaintHelena, CountryNames.SaintKittsAndNevis, CountryNames.SaintLucia,
            CountryNames.SaintVincentAndTheGrenadines, CountryNames.SanMarino, CountryNames.SaoTomePrincipe,
            CountryNames.SaudiArabia, CountryNames.Senegal, CountryNames.Serbia,
            CountryNames.Seychelles, CountryNames.SierraLeone, CountryNames.Singapore,
            CountryNames.Slovakia, CountryNames.Slovenia, CountryNames.Somalia, 
            CountryNames.SouthAfrica, CountryNames.SouthKorea, CountryNames.SouthSudan,
            CountryNames.Spain, CountryNames.SriLanka, CountryNames.Sudan,
            CountryNames.Suriname, CountryNames.Sweden, CountryNames.Switzerland,
            CountryNames.Syria, CountryNames.Taiwan, CountryNames.Tajikistan,
            CountryNames.Tanzania, CountryNames.Thailand, CountryNames.TheBahamas,
            CountryNames.TimorLeste, CountryNames.Togo, CountryNames.TrinidadAndTobago,
            CountryNames.Tunisia, CountryNames.Turkey, CountryNames.Turkmenistan,
            CountryNames.Uganda, CountryNames.Ukraine, CountryNames.UnitedArabEmirates,
            CountryNames.UnitedKingdom, CountryNames.UnitedStates, CountryNames.Uruguay,
            CountryNames.Uzbekistan, CountryNames.Venezuela, CountryNames.Vietnam,
            CountryNames.WesternSahara, CountryNames.Yemen, CountryNames.Zambia,
            CountryNames.Zimbabwe
        };

        public static CountryDTO[] GetCountryDTOs() => new CountryDTO[] {
            new CountryDTO(Countries.Afghanistan, CountryNames.Afghanistan, CountryFlags_Square64.Flag_of_Afghanistan_Flat_Square_64x64),
            new CountryDTO(Countries.Albania, CountryNames.Albania, CountryFlags_Square64.Flag_of_Albania_Flat_Square_64x64),
            new CountryDTO(Countries.Algeria, CountryNames.Algeria, CountryFlags_Square64.Flag_of_Algeria_Flat_Square_64x64),
            new CountryDTO(Countries.Andorra, CountryNames.Andorra, CountryFlags_Square64.Flag_of_Andorra_Flat_Square_64x64),
            new CountryDTO(Countries.Angola, CountryNames.Angola, CountryFlags_Square64.Flag_of_Angola_Flat_Square_64x64),
            new CountryDTO(Countries.AntiguaAndBarbuda, CountryNames.AntiguaAndBarbuda, CountryFlags_Square64.Flag_of_Antigua_and_Barbuda_Flat_Square_64x64),
            new CountryDTO(Countries.Argentina, CountryNames.Argentina, CountryFlags_Square64.Flag_of_Argentina_Flat_Square_64x64),
            new CountryDTO(Countries.Armenia, CountryNames.Armenia, CountryFlags_Square64.Flag_of_Armenia_Flat_Square_64x64),
            new CountryDTO(Countries.Austria, CountryNames.Austria, CountryFlags_Square64.Flag_of_Austria_Flat_Square_64x64),
            new CountryDTO(Countries.Azerbaijan, CountryNames.Azerbaijan, CountryFlags_Square64.Flag_of_Azerbaijan_Flat_Square_64x64),
            new CountryDTO(Countries.Bahrain, CountryNames.Bahrain, CountryFlags_Square64.Flag_of_Bahrain_Flat_Square_64x64),
            new CountryDTO(Countries.Bangladesh, CountryNames.Bangladesh, CountryFlags_Square64.Flag_of_Bangladesh_Flat_Square_64x64),
            new CountryDTO(Countries.Barbados, CountryNames.Barbados, CountryFlags_Square64.Flag_of_Barbados_Flat_Square_64x64),
            new CountryDTO(Countries.Belarus, CountryNames.Belarus, CountryFlags_Square64.Flag_of_Belarus_Flat_Square_64x64),
            new CountryDTO(Countries.Belgium, CountryNames.Belgium, CountryFlags_Square64.Flag_of_Belgium_Flat_Square_64x64),
            new CountryDTO(Countries.Belize, CountryNames.Belize, CountryFlags_Square64.Flag_of_Belize_Flat_Square_64x64),
            new CountryDTO(Countries.Benin, CountryNames.Benin, CountryFlags_Square64.Flag_of_Benin_Flat_Square_64x64),
            new CountryDTO(Countries.Bhutan, CountryNames.Bhutan, CountryFlags_Square64.Flag_of_Bhutan_Flat_Square_64x64),
            new CountryDTO(Countries.Bolivia, CountryNames.Bolivia, CountryFlags_Square64.Flag_of_Bolivia_Flat_Square_64x64),
            new CountryDTO(Countries.BosniaAndHerzegovina, CountryNames.BosniaAndHerzegovina, CountryFlags_Square64.Flag_of_Bosnia_and_Herzegovina_Flat_Square_64x64),
            new CountryDTO(Countries.Botswana, CountryNames.Botswana, CountryFlags_Square64.Flag_of_Botswana_Flat_Square_64x64),
            new CountryDTO(Countries.Brazil, CountryNames.Brazil, CountryFlags_Square64.Flag_of_Brazil_Flat_Square_64x64),
            new CountryDTO(Countries.Brunei, CountryNames.Brunei, CountryFlags_Square64.Flag_of_Brunei_Flat_Square_64x64),
            new CountryDTO(Countries.Bulgaria, CountryNames.Bulgaria, CountryFlags_Square64.Flag_of_Bulgaria_Flat_Square_64x64),
            new CountryDTO(Countries.BurkinaFaso, CountryNames.BurkinaFaso, CountryFlags_Square64.Flag_of_Burkina_Faso_Flat_Square_64x64),
            new CountryDTO(Countries.Burundi, CountryNames.Burundi, CountryFlags_Square64.Flag_of_Burundi_Flat_Square_64x64),
            new CountryDTO(Countries.CaboVerde, CountryNames.CaboVerde, CountryFlags_Square64.Flag_of_Cape_Verde_Flat_Square_64x64),
            new CountryDTO(Countries.Cambodia, CountryNames.Cambodia, CountryFlags_Square64.Flag_of_Cambodia_Flat_Square_64x64),
            new CountryDTO(Countries.Cameroon, CountryNames.Cameroon, CountryFlags_Square64.Flag_of_Cameroon_Flat_Square_64x64),
            new CountryDTO(Countries.Canada, CountryNames.Canada, CountryFlags_Square64.Flag_of_Canada_Flat_Square_64x64),
            new CountryDTO(Countries.CentralAfricanRepublic, CountryNames.CentralAfricanRepublic, CountryFlags_Square64.Flag_of_Central_African_Republic_Flat_Square_64x64),
            new CountryDTO(Countries.Chad, CountryNames.Chad, CountryFlags_Square64.Flag_of_Chad_Flat_Square_64x64),
            new CountryDTO(Countries.ChannelIslands, CountryNames.ChannelIslands, CountryFlags_Square64.No_Image_64x64),
            new CountryDTO(Countries.Chile, CountryNames.Chile, CountryFlags_Square64.Flag_of_Chile_Flat_Square_64x64),
            new CountryDTO(Countries.China, CountryNames.China, CountryFlags_Square64.Flag_of_Peoples_Republic_of_China_Flat_Square_64x64),
            new CountryDTO(Countries.Colombia, CountryNames.Colombia, CountryFlags_Square64.Flag_of_Colombia_Flat_Square_64x64),
            new CountryDTO(Countries.Comoros, CountryNames.Comoros, CountryFlags_Square64.Flag_of_Comoros_Flat_Square_64x64),
            new CountryDTO(Countries.Congo, CountryNames.Congo, CountryFlags_Square64.Flag_of_Republic_of_Congo_Flat_Square_64x64),
            new CountryDTO(Countries.CostaRica, CountryNames.CostaRica, CountryFlags_Square64.Flag_of_Costa_Rica_Flat_Square_64x64),
            new CountryDTO(Countries.CôtedIvoire, CountryNames.CôtedIvoire, CountryFlags_Square64.Flag_of_Côte_dIvoire_Flat_Square_64x64),
            new CountryDTO(Countries.Croatia, CountryNames.Croatia, CountryFlags_Square64.Flag_of_Croatia_Flat_Square_64x64),
            new CountryDTO(Countries.Cuba, CountryNames.Cuba, CountryFlags_Square64.Flag_of_Cuba_Flat_Square_64x64),
            new CountryDTO(Countries.Cyprus, CountryNames.Cyprus, CountryFlags_Square64.Flag_of_Cyprus_Flat_Square_64x64),
            new CountryDTO(Countries.CzechRepublic, CountryNames.CzechRepublic, CountryFlags_Square64.Flag_of_Czech_Republic_Flat_Square_64x64),
            new CountryDTO(Countries.Denmark, CountryNames.Denmark, CountryFlags_Square64.Flag_of_Denmark_Flat_Square_64x64),
            new CountryDTO(Countries.Djibouti, CountryNames.Djibouti, CountryFlags_Square64.Flag_of_Djibouti_Flat_Square_64x64),
            new CountryDTO(Countries.Dominica, CountryNames.Dominica, CountryFlags_Square64.Flag_of_Dominica_Flat_Square_64x64),
            new CountryDTO(Countries.DominicanRepublic, CountryNames.DominicanRepublic, CountryFlags_Square64.Flag_of_Dominican_Republic_Flat_Square_64x64),
            new CountryDTO(Countries.DRCongo, CountryNames.DRCongo, CountryFlags_Square64.Flag_of_Democratic_Republic_of_Congo_Flat_Square_64x64),
            new CountryDTO(Countries.Ecuador, CountryNames.Ecuador, CountryFlags_Square64.Flag_of_Ecuador_Flat_Square_64x64),
            new CountryDTO(Countries.Egypt, CountryNames.Egypt, CountryFlags_Square64.Flag_of_Egypt_Flat_Square_64x64),
            new CountryDTO(Countries.ElSalvador, CountryNames.ElSalvador, CountryFlags_Square64.Flag_of_El_Salvador_Flat_Square_64x64),
            new CountryDTO(Countries.EquatorialGuinea, CountryNames.EquatorialGuinea, CountryFlags_Square64.Flag_of_Equatorial_Guinea_Flat_Square_64x64),
            new CountryDTO(Countries.Eritrea, CountryNames.Eritrea, CountryFlags_Square64.Flag_of_Eritrea_Flat_Square_64x64),
            new CountryDTO(Countries.Estonia, CountryNames.Estonia, CountryFlags_Square64.Flag_of_Estonia_Flat_Square_64x64),
            new CountryDTO(Countries.Eswatini, CountryNames.Eswatini, CountryFlags_Square64.Flag_of_Eswatini_Flat_Square_64x64),
            new CountryDTO(Countries.Ethiopia, CountryNames.Ethiopia, CountryFlags_Square64.Flag_of_Ethiopia_Flat_Square_64x64),
            new CountryDTO(Countries.FaeroeIslands, CountryNames.FaeroeIslands, CountryFlags_Square64.Flag_of_Faroe_Islands_Flat_Square_64x64),
            new CountryDTO(Countries.Finland, CountryNames.Finland, CountryFlags_Square64.Flag_of_Finland_Flat_Square_64x64),
            new CountryDTO(Countries.France, CountryNames.France, CountryFlags_Square64.Flag_of_France_Flat_Square_64x64),
            new CountryDTO(Countries.FrenchGuiana, CountryNames.FrenchGuiana, CountryFlags_Square64.Flag_of_French_Guiana_Flat_Square_64x64),
            new CountryDTO(Countries.Gabon, CountryNames.Gabon, CountryFlags_Square64.Flag_of_Gabon_Flat_Square_64x64),
            new CountryDTO(Countries.Gambia, CountryNames.Gambia, CountryFlags_Square64.Flag_of_Gambia_Flat_Square_64x64),
            new CountryDTO(Countries.Georgia, CountryNames.Georgia, CountryFlags_Square64.Flag_of_Georgia_Flat_Square_64x64),
            new CountryDTO(Countries.Germany, CountryNames.Germany, CountryFlags_Square64.Flag_of_Germany_Flat_Square_64x64),
            new CountryDTO(Countries.Ghana, CountryNames.Ghana, CountryFlags_Square64.Flag_of_Ghana_Flat_Square_64x64),
            new CountryDTO(Countries.Gibraltar, CountryNames.Gibraltar, CountryFlags_Square64.Flag_of_Gibraltar_Flat_Square_64x64),
            new CountryDTO(Countries.Greece, CountryNames.Greece, CountryFlags_Square64.Flag_of_Greece_Flat_Square_64x64),
            new CountryDTO(Countries.Grenada, CountryNames.Grenada, CountryFlags_Square64.Flag_of_Grenada_Flat_Square_64x64),
            new CountryDTO(Countries.Guatemala, CountryNames.Guatemala, CountryFlags_Square64.Flag_of_Guatemala_Flat_Square_64x64),
            new CountryDTO(Countries.Guinea, CountryNames.Guinea, CountryFlags_Square64.Flag_of_Guinea_Flat_Square_64x64),
            new CountryDTO(Countries.GuineaBissau, CountryNames.GuineaBissau, CountryFlags_Square64.Flag_of_Guinea_Bissau_Flat_Square_64x64),
            new CountryDTO(Countries.Guyana, CountryNames.Guyana, CountryFlags_Square64.Flag_of_Guyana_Flat_Square_64x64),
            new CountryDTO(Countries.Haiti, CountryNames.Haiti, CountryFlags_Square64.Flag_of_Haiti_Flat_Square_64x64),
            new CountryDTO(Countries.HolySee, CountryNames.HolySee, CountryFlags_Square64.Flag_of_Vatican_City_Flat_Square_64x64),
            new CountryDTO(Countries.Honduras, CountryNames.Honduras, CountryFlags_Square64.Flag_of_Honduras_Flat_Square_64x64),
            new CountryDTO(Countries.HongKong, CountryNames.HongKong, CountryFlags_Square64.Flag_of_Hong_Kong_Flat_Square_64x64),
            new CountryDTO(Countries.Hungary, CountryNames.Hungary, CountryFlags_Square64.Flag_of_Hungary_Flat_Square_64x64),
            new CountryDTO(Countries.Iceland, CountryNames.Iceland, CountryFlags_Square64.Flag_of_Iceland_Flat_Square_64x64),
            new CountryDTO(Countries.India, CountryNames.India, CountryFlags_Square64.Flag_of_India_Flat_Square_64x64),
            new CountryDTO(Countries.Indonesia, CountryNames.Indonesia, CountryFlags_Square64.Flag_of_Indonesia_Flat_Square_64x64),
            new CountryDTO(Countries.Iran, CountryNames.Iran, CountryFlags_Square64.Flag_of_Iran_Flat_Square_64x64),
            new CountryDTO(Countries.Iraq, CountryNames.Iraq, CountryFlags_Square64.Flag_of_Iraq_Flat_Square_64x64),
            new CountryDTO(Countries.Ireland, CountryNames.Ireland, CountryFlags_Square64.Flag_of_Ireland_Flat_Square_64x64),
            new CountryDTO(Countries.IsleOfMan, CountryNames.IsleofMan, CountryFlags_Square64.Flag_of_Isle_of_Mann_Flat_Square_64x64),
            new CountryDTO(Countries.Israel, CountryNames.Israel, CountryFlags_Square64.Flag_of_Israel_Flat_Square_64x64),
            new CountryDTO(Countries.Italy, CountryNames.Italy, CountryFlags_Square64.Flag_of_Italy_Flat_Square_64x64),
            new CountryDTO(Countries.Jamaica, CountryNames.Jamaica, CountryFlags_Square64.Flag_of_Jamaica_Flat_Square_64x64),
            new CountryDTO(Countries.Japan, CountryNames.Japan, CountryFlags_Square64.Flag_of_Japan_Flat_Square_64x64),
            new CountryDTO(Countries.Jordan, CountryNames.Jordan, CountryFlags_Square64.Flag_of_Jordan_Flat_Square_64x64),
            new CountryDTO(Countries.Kazakhstan, CountryNames.Kazakhstan, CountryFlags_Square64.Flag_of_Kazakhstan_Flat_Square_64x64),
            new CountryDTO(Countries.Kenya, CountryNames.Kenya, CountryFlags_Square64.Flag_of_Kenya_Flat_Square_64x64),
            new CountryDTO(Countries.Kuwait, CountryNames.Kuwait, CountryFlags_Square64.Flag_of_Kuwait_Flat_Square_64x64),
            new CountryDTO(Countries.Kyrgyzstan, CountryNames.Kyrgyzstan, CountryFlags_Square64.Flag_of_Kyrgyzstan_Flat_Square_64x64),
            new CountryDTO(Countries.Laos, CountryNames.Laos, CountryFlags_Square64.Flag_of_Laos_Flat_Square_64x64),
            new CountryDTO(Countries.Latvia, CountryNames.Latvia, CountryFlags_Square64.Flag_of_Latvia_Flat_Square_64x64),
            new CountryDTO(Countries.Lebanon, CountryNames.Lebanon, CountryFlags_Square64.Flag_of_Lebanon_Flat_Square_64x64),
            new CountryDTO(Countries.Lesotho, CountryNames.Lesotho, CountryFlags_Square64.Flag_of_Lesotho_Flat_Square_64x64),
            new CountryDTO(Countries.Liberia, CountryNames.Liberia, CountryFlags_Square64.Flag_of_Liberia_Flat_Square_64x64),
            new CountryDTO(Countries.Libya, CountryNames.Libya, CountryFlags_Square64.Flag_of_Libya_Flat_Square_64x64),
            new CountryDTO(Countries.Liechtenstein, CountryNames.Liechtenstein, CountryFlags_Square64.Flag_of_Liechtenstein_Flat_Square_64x64),
            new CountryDTO(Countries.Lithuania, CountryNames.Lithuania, CountryFlags_Square64.Flag_of_Lithuania_Flat_Square_64x64),
            new CountryDTO(Countries.Luxembourg, CountryNames.Luxembourg, CountryFlags_Square64.Flag_of_Luxembourg_Flat_Square_64x64),
            new CountryDTO(Countries.Macao, CountryNames.Macao, CountryFlags_Square64.Flag_of_Macau_Flat_Square_64x64),
            new CountryDTO(Countries.Madagascar, CountryNames.Madagascar, CountryFlags_Square64.Flag_of_Madagascar_Flat_Square_64x64),
            new CountryDTO(Countries.Malawi, CountryNames.Malawi, CountryFlags_Square64.Flag_of_Malawi_Flat_Square_64x64),
            new CountryDTO(Countries.Malaysia, CountryNames.Malaysia, CountryFlags_Square64.Flag_of_Malaysia_Flat_Square_64x64),
            new CountryDTO(Countries.Maldives, CountryNames.Maldives, CountryFlags_Square64.Flag_of_Maldives_Flat_Square_64x64),
            new CountryDTO(Countries.Mali, CountryNames.Mali, CountryFlags_Square64.Flag_of_Mali_Flat_Square_64x64),
            new CountryDTO(Countries.Malta, CountryNames.Malta, CountryFlags_Square64.Flag_of_Malta_Flat_Square_64x64),
            new CountryDTO(Countries.Mauritania, CountryNames.Mauritania, CountryFlags_Square64.Flag_of_Mauritania_Flat_Square_64x64),
            new CountryDTO(Countries.Mauritius, CountryNames.Mauritius, CountryFlags_Square64.Flag_of_Mauritius_Flat_Square_64x64),
            new CountryDTO(Countries.Mayotte, CountryNames.Mayotte, CountryFlags_Square64.Flag_of_Mayotte_Flat_Square_64x64),
            new CountryDTO(Countries.Mexico, CountryNames.Mexico, CountryFlags_Square64.Flag_of_Mexico_Flat_Square_64x64),
            new CountryDTO(Countries.Moldova, CountryNames.Moldova, CountryFlags_Square64.Flag_of_Moldova_Flat_Square_64x64),
            new CountryDTO(Countries.Monaco, CountryNames.Monaco, CountryFlags_Square64.Flag_of_Monaco_Flat_Square_64x64),
            new CountryDTO(Countries.Mongolia, CountryNames.Mongolia, CountryFlags_Square64.Flag_of_Mongolia_Flat_Square_64x64),
            new CountryDTO(Countries.Montenegro, CountryNames.Montenegro, CountryFlags_Square64.Flag_of_Montenegro_Flat_Square_64x64),
            new CountryDTO(Countries.Morocco, CountryNames.Morocco, CountryFlags_Square64.Flag_of_Morocco_Flat_Square_64x64),
            new CountryDTO(Countries.Mozambique, CountryNames.Mozambique, CountryFlags_Square64.Flag_of_Mozambique_Flat_Square_64x64),
            new CountryDTO(Countries.Myanmar, CountryNames.Myanmar, CountryFlags_Square64.Flag_of_Myanmar_Flat_Square_64x64),
            new CountryDTO(Countries.Namibia, CountryNames.Namibia, CountryFlags_Square64.Flag_of_Namibia_Flat_Square_64x64),
            new CountryDTO(Countries.Nepal, CountryNames.Nepal, CountryFlags_Square64.Flag_of_Nepal_Flat_Square_64x64),
            new CountryDTO(Countries.Netherlands, CountryNames.Netherlands, CountryFlags_Square64.Flag_of_Netherlands_Flat_Square_64x64),
            new CountryDTO(Countries.Nicaragua, CountryNames.Nicaragua, CountryFlags_Square64.Flag_of_Nicaragua_Flat_Square_64x64),
            new CountryDTO(Countries.Niger, CountryNames.Niger, CountryFlags_Square64.Flag_of_Niger_Flat_Square_64x64),
            new CountryDTO(Countries.Nigeria, CountryNames.Nigeria, CountryFlags_Square64.Flag_of_Nigeria_Flat_Square_64x64),
            new CountryDTO(Countries.NorthKorea, CountryNames.NorthKorea, CountryFlags_Square64.Flag_of_North_Korea_Flat_Square_64x64),
            new CountryDTO(Countries.NorthMacedonia, CountryNames.NorthMacedonia, CountryFlags_Square64.Flag_of_North_Macedonia_Flat_Square_64x64),
            new CountryDTO(Countries.Norway, CountryNames.Norway, CountryFlags_Square64.Flag_of_Norway_Flat_Square_64x64),
            new CountryDTO(Countries.Oman, CountryNames.Oman, CountryFlags_Square64.Flag_of_Oman_Flat_Square_64x64),
            new CountryDTO(Countries.Pakistan, CountryNames.Pakistan, CountryFlags_Square64.Flag_of_Pakistan_Flat_Square_64x64),
            new CountryDTO(Countries.Palestine, CountryNames.Palestine, CountryFlags_Square64.Flag_of_Palestine_Flat_Square_64x64),
            new CountryDTO(Countries.Panama, CountryNames.Panama, CountryFlags_Square64.Flag_of_Panama_Flat_Square_64x64),
            new CountryDTO(Countries.Paraguay, CountryNames.Paraguay, CountryFlags_Square64.Flag_of_Paraguay_Flat_Square_64x64),
            new CountryDTO(Countries.Peru, CountryNames.Peru, CountryFlags_Square64.Flag_of_Peru_Flat_Square_64x64),
            new CountryDTO(Countries.Philippines, CountryNames.Philippines, CountryFlags_Square64.Flag_of_Philippines_Flat_Square_64x64),
            new CountryDTO(Countries.Poland, CountryNames.Poland, CountryFlags_Square64.Flag_of_Poland_Flat_Square_64x64),
            new CountryDTO(Countries.Portugal, CountryNames.Portugal, CountryFlags_Square64.Flag_of_Portugal_Flat_Square_64x64),
            new CountryDTO(Countries.Qatar, CountryNames.Qatar, CountryFlags_Square64.Flag_of_Qatar_Flat_Square_64x64),
            new CountryDTO(Countries.Réunion, CountryNames.Réunion, CountryFlags_Square64.Flag_of_Reunion_Radiant_Volcano_Flat_Square_64x64),
            new CountryDTO(Countries.Romania, CountryNames.Romania, CountryFlags_Square64.Flag_of_Romania_Flat_Square_64x64),
            new CountryDTO(Countries.Russia, CountryNames.Russia, CountryFlags_Square64.Flag_of_Russia_Flat_Square_64x64),
            new CountryDTO(Countries.Rwanda, CountryNames.Rwanda, CountryFlags_Square64.Flag_of_Rwanda_Flat_Square_64x64),
            new CountryDTO(Countries.SaintHelena, CountryNames.SaintHelena, CountryFlags_Square64.Flag_of_Saint_Helena_Flat_Square_64x64),
            new CountryDTO(Countries.SaintKittsAndNevis, CountryNames.SaintKittsAndNevis, CountryFlags_Square64.Flag_of_Saint_Kitts_and_Nevis_Flat_Square_64x64),
            new CountryDTO(Countries.SaintLucia, CountryNames.SaintLucia, CountryFlags_Square64.Flag_of_Saint_Lucia_Flat_Square_64x64),
            new CountryDTO(Countries.SaintVincentAndTheGrenadines, CountryNames.SaintVincentAndTheGrenadines, CountryFlags_Square64.Flag_of_Saint_Vincent_and_the_Grenadines_Flat_Square_64x64),
            new CountryDTO(Countries.SanMarino, CountryNames.SanMarino, CountryFlags_Square64.Flag_of_San_Marino_Flat_Square_64x64),
            new CountryDTO(Countries.SaoTomePrincipe, CountryNames.SaoTomePrincipe, CountryFlags_Square64.Flag_of_Sao_Tome_and_Principe_Flat_Square_64x64),
            new CountryDTO(Countries.SaudiArabia, CountryNames.SaudiArabia, CountryFlags_Square64.Flag_of_Saudi_Arabia_Flat_Square_64x64),
            new CountryDTO(Countries.Senegal, CountryNames.Senegal, CountryFlags_Square64.Flag_of_Senegal_Flat_Square_64x64),
            new CountryDTO(Countries.Serbia, CountryNames.Serbia, CountryFlags_Square64.Flag_of_Serbia_Flat_Square_64x64),
            new CountryDTO(Countries.Seychelles, CountryNames.Seychelles, CountryFlags_Square64.Flag_of_Seychelles_Flat_Square_64x64),
            new CountryDTO(Countries.SierraLeone, CountryNames.SierraLeone, CountryFlags_Square64.Flag_of_Sierra_Leone_Flat_Square_64x64),
            new CountryDTO(Countries.Singapore, CountryNames.Singapore, CountryFlags_Square64.Flag_of_Singapore_Flat_Square_64x64),
            new CountryDTO(Countries.Slovakia, CountryNames.Slovakia, CountryFlags_Square64.Flag_of_Slovakia_Flat_Square_64x64),
            new CountryDTO(Countries.Slovenia, CountryNames.Slovenia, CountryFlags_Square64.Flag_of_Slovenia_Flat_Square_64x64),
            new CountryDTO(Countries.Somalia, CountryNames.Somalia, CountryFlags_Square64.Flag_of_Somalia_Flat_Square_64x64),
            new CountryDTO(Countries.SouthAfrica, CountryNames.SouthAfrica, CountryFlags_Square64.Flag_of_South_Africa_Flat_Square_64x64),
            new CountryDTO(Countries.SouthKorea, CountryNames.SouthKorea, CountryFlags_Square64.Flag_of_South_Korea_Flat_Square_64x64),
            new CountryDTO(Countries.SouthSudan, CountryNames.SouthSudan, CountryFlags_Square64.Flag_of_South_Sudan_Flat_Square_64x64),
            new CountryDTO(Countries.Spain, CountryNames.Spain, CountryFlags_Square64.Flag_of_Spain_Flat_Square_64x64),
            new CountryDTO(Countries.SriLanka, CountryNames.SriLanka, CountryFlags_Square64.Flag_of_Sri_Lanka_Flat_Square_64x64),
            new CountryDTO(Countries.Sudan, CountryNames.Sudan, CountryFlags_Square64.Flag_of_Sudan_Flat_Square_64x64),
            new CountryDTO(Countries.Suriname, CountryNames.Suriname, CountryFlags_Square64.Flag_of_Suriname_Flat_Square_64x64),
            new CountryDTO(Countries.Sweden, CountryNames.Sweden, CountryFlags_Square64.Flag_of_Sweden_Flat_Square_64x64),
            new CountryDTO(Countries.Switzerland, CountryNames.Switzerland, CountryFlags_Square64.Flag_of_Switzerland_Flat_Square_64x64),
            new CountryDTO(Countries.Syria, CountryNames.Syria, CountryFlags_Square64.Flag_of_Syria_Flat_Square_64x64),
            new CountryDTO(Countries.Taiwan, CountryNames.Taiwan, CountryFlags_Square64.Flag_of_Taiwan_Republic_of_China_Flat_Square_64x64),
            new CountryDTO(Countries.Tajikistan, CountryNames.Tajikistan, CountryFlags_Square64.Flag_of_Tajikistan_Flat_Square_64x64),
            new CountryDTO(Countries.Tanzania, CountryNames.Tanzania, CountryFlags_Square64.Flag_of_Tanzania_Flat_Square_64x64),
            new CountryDTO(Countries.Thailand, CountryNames.Thailand, CountryFlags_Square64.Flag_of_Thailand_Flat_Square_64x64),
            new CountryDTO(Countries.TheBahamas, CountryNames.TheBahamas, CountryFlags_Square64.Flag_of_Bahamas_Flat_Square_64x64),
            new CountryDTO(Countries.TimorLeste, CountryNames.TimorLeste, CountryFlags_Square64.Flag_of_East_Timor_Flat_Square_64x64),
            new CountryDTO(Countries.Togo, CountryNames.Togo, CountryFlags_Square64.Flag_of_Togo_Flat_Square_64x64),
            new CountryDTO(Countries.TrinidadAndTobago, CountryNames.TrinidadAndTobago, CountryFlags_Square64.Flag_of_Trinidad_and_Tobago_Flat_Square_64x64),
            new CountryDTO(Countries.Tunisia, CountryNames.Tunisia, CountryFlags_Square64.Flag_of_Tunisia_Flat_Square_64x64),
            new CountryDTO(Countries.Turkey, CountryNames.Turkey, CountryFlags_Square64.Flag_of_Turkey_Flat_Square_64x64),
            new CountryDTO(Countries.Turkmenistan, CountryNames.Turkmenistan, CountryFlags_Square64.Flag_of_Turkmenistan_Flat_Square_64x64),
            new CountryDTO(Countries.Uganda, CountryNames.Uganda, CountryFlags_Square64.Flag_of_Uganda_Flat_Square_64x64),
            new CountryDTO(Countries.Ukraine, CountryNames.Ukraine, CountryFlags_Square64.Flag_of_Ukraine_Flat_Square_64x64),
            new CountryDTO(Countries.UnitedArabEmirates, CountryNames.UnitedArabEmirates, CountryFlags_Square64.Flag_of_United_Arab_Emirates_Flat_Square_64x64),
            new CountryDTO(Countries.UnitedKingdom, CountryNames.UnitedKingdom, CountryFlags_Square64.Flag_of_United_Kingdom_Flat_Square_64x64),
            new CountryDTO(Countries.UnitedStates, CountryNames.UnitedStates, CountryFlags_Square64.Flag_of_United_States_Flat_Square_64x64),
            new CountryDTO(Countries.Uruguay, CountryNames.Uruguay, CountryFlags_Square64.Flag_of_Uruguay_Flat_Square_64x64),
            new CountryDTO(Countries.Uzbekistan, CountryNames.Uzbekistan, CountryFlags_Square64.Flag_of_Uzbekistan_Flat_Square_64x64),
            new CountryDTO(Countries.Venezuela, CountryNames.Venezuela, CountryFlags_Square64.Flag_of_Venezuela_Flat_Square_64x64),
            new CountryDTO(Countries.Vietnam, CountryNames.Vietnam, CountryFlags_Square64.Flag_of_Vietnam_Flat_Square_64x64),
            new CountryDTO(Countries.WesternSahara, CountryNames.WesternSahara, CountryFlags_Square64.No_Image_64x64),
            new CountryDTO(Countries.Yemen, CountryNames.Yemen, CountryFlags_Square64.Flag_of_Yemen_Flat_Square_64x64),
            new CountryDTO(Countries.Zambia, CountryNames.Zambia, CountryFlags_Square64.Flag_of_Zambia_Flat_Square_64x64),
            new CountryDTO(Countries.Zimbabwe, CountryNames.Zimbabwe, CountryFlags_Square64.Flag_of_Zimbabwe_Flat_Square_64x64)
        };

        public static string[] GetDayOfWeekNames() => new string[] {
            DayOfWeekNames.Sunday, DayOfWeekNames.Monday, DayOfWeekNames.Tuesday,
            DayOfWeekNames.Wednesday, DayOfWeekNames.Thursday, DayOfWeekNames.Friday, 
            DayOfWeekNames.Saturday
        };

        public static string[] GetMonthNames() => new string[] {
            MonthNames.January, MonthNames.February, MonthNames.March,
            MonthNames.April, MonthNames.May, MonthNames.June,
            MonthNames.July, MonthNames.August, MonthNames.September,
            MonthNames.October, MonthNames.November, MonthNames.December
        };

        public static string[] GetPaperSizeNames() => new string[] {
            PaperSizeNames.Legal, PaperSizeNames.Letter, PaperSizeNames.Tabloid, 
            PaperSizeNames.A0, PaperSizeNames.A1, PaperSizeNames.A2, 
            PaperSizeNames.A3, PaperSizeNames.A4, PaperSizeNames.A5
        };
    }
}
